### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by penguoir** [penguoir/tada-todo#3]
You should be able to manage projects. Have a sidebar with projects that navigate the url to `/project/<id>` and a button to create a new project.

### Tasks
- [x] Sidebar
- [x] <Project /> component (for sidebar)
- [x] Create new project button (opens a modal which allows creation)
- [x] Hamburger menu to allow editing (in sidebar and next to title of the project)
- [x] Documentation of the updates and components
